version: '3.8'
services:
  dashboard:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - default
    restart: unless-stopped

  ollama:
    image: "ollama/ollama"
    volumes:
      - "ollama:/root/.ollama"
    expose:
      - "11434"
    networks:
      - default
    restart: unless-stopped

volumes:
  ollama:

networks:
  default:
