version: '3.8'
services:
  dashboard:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - default

  ollama:
    image: "ollama/ollama:rocm"
    volumes:
      - "ollama:/root/.ollama"
    expose:
      - "11434"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    networks:
      - default
    restart: unless-stopped

volumes:
  ollama:

networks:
  default: