version: '3.8'
services:
  dashboard:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - default

  ollama:
    image: "ollama/ollama"
    volumes:
      - "ollama:/root/.ollama"
    expose:
      - "11434"
    networks:
      - default
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  ollama:

networks:
  default:
